---
name: Build & Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "example-service/**"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Check out the repository to the GitHub Actions runner
      - name: Checkout repository
        uses: actions/checkout@v3
      # Login to the GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Build and push the Docker image to the GitHub Container Registry
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./example-service
          push: true
          tags: ghcr.io/${{ github.repository }}/webserver:latest
